version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
